spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/ptit?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwtSecret=${JWT_SECRET:DayLaMotChuoiBiMatCuaPtitRatDaiVaAnToanDeMaHoaToken1234567890DayLaMotChuoiBiMatCuaPtitRatDaiVaAnToanDeMaHoaToken1234567890}
app.jwtExpirationMs=86400000

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:lamtrunghieuq@gmail.com}
spring.mail.password=${MAIL_PASSWORD:dxiurcgwtbuopaql}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true